export type Wine = {
  id: string
  name: string
  winery: string
  vintage: number
  region: string
  country: string
  grapes: string[]
  type: 'white' | 'rosé' | 'sparkling' | 'red' | 'dessert'
  ratings: {
    appearance?: number
    nose?: number
    palate?: number
    finish?: number
    value?: number
    overall?: number
  }
  tastingNotes?: string
  foodPairing?: string
  wouldBuyAgain?: boolean
}

export const mockWines: Wine[] = [
  {
    id: '1',
    name: 'Sauvignon Blanc',
    winery: 'Cloudy Bay',
    vintage: 2022,
    region: 'Marlborough',
    country: 'New Zealand',
    grapes: ['Sauvignon Blanc'],
    type: 'white',
    ratings: {
      appearance: 5,
      nose: 4,
      palate: 5,
      finish: 4,
      value: 5,
      overall: 8,
    },
    tastingNotes: 'Crisp citrus notes with herbaceous undertones',
    foodPairing: 'Seafood, light salads',
    wouldBuyAgain: true,
  },
  {
    id: '2',
    name: 'Prosecco',
    winery: 'Valdobbiadene',
    vintage: 2023,
    region: 'Veneto',
    country: 'Italy',
    grapes: ['Glera'],
    type: 'sparkling',
    ratings: {
      appearance: 4,
      nose: 4,
      palate: 4,
      finish: 3,
      value: 4,
      overall: 7,
    },
    tastingNotes: 'Light and refreshing with green apple notes',
    foodPairing: 'Appetizers, desserts',
    wouldBuyAgain: true,
  },
  {
    id: '3',
    name: 'Rosé de Provence',
    winery: 'Château d\'Esclans',
    vintage: 2022,
    region: 'Provence',
    country: 'France',
    grapes: ['Grenache', 'Syrah', 'Mourvèdre'],
    type: 'rosé',
    ratings: {
      appearance: 5,
      nose: 5,
      palate: 4,
      finish: 4,
      value: 4,
      overall: 8,
    },
    tastingNotes: 'Dry and elegant with strawberry and stone fruit',
    foodPairing: 'Summer dishes, grilled vegetables',
    wouldBuyAgain: true,
  },
  {
    id: '4',
    name: 'Chardonnay',
    winery: 'Chablis William Fèvre',
    vintage: 2021,
    region: 'Chablis',
    country: 'France',
    grapes: ['Chardonnay'],
    type: 'white',
    ratings: {
      appearance: 4,
      nose: 4,
      palate: 5,
      finish: 4,
      value: 4,
      overall: 8,
    },
    tastingNotes: 'Mineral-driven with green apple and lemon',
    foodPairing: 'Oysters, shellfish, white fish',
    wouldBuyAgain: true,
  },
  {
    id: '5',
    name: 'Albariño',
    winery: 'Martín Códax',
    vintage: 2022,
    region: 'Rías Baixas',
    country: 'Spain',
    grapes: ['Albariño'],
    type: 'white',
    ratings: {
      appearance: 5,
      nose: 4,
      palate: 4,
      finish: 4,
      value: 5,
      overall: 8,
    },
    tastingNotes: 'Bright acidity with peach and citrus',
    foodPairing: 'Seafood paella, grilled fish',
    wouldBuyAgain: true,
  },
  {
    id: '6',
    name: 'Pinot Grigio',
    winery: 'Ecco Domani',
    vintage: 2023,
    region: 'Friuli-Venezia Giulia',
    country: 'Italy',
    grapes: ['Pinot Grigio'],
    type: 'white',
    ratings: {
      appearance: 4,
      nose: 3,
      palate: 3,
      finish: 3,
      value: 3,
      overall: 6,
    },
    tastingNotes: 'Light and approachable',
    foodPairing: 'Light pasta, summer fare',
    wouldBuyAgain: false,
  },
  {
    id: '7',
    name: 'Grüner Veltliner',
    winery: 'Hirtzberger',
    vintage: 2022,
    region: 'Danube Valley',
    country: 'Austria',
    grapes: ['Grüner Veltliner'],
    type: 'white',
    ratings: {
      appearance: 5,
      nose: 5,
      palate: 5,
      finish: 4,
      value: 4,
      overall: 9,
    },
    tastingNotes: 'Complex with white pepper and stone fruit',
    foodPairing: 'Asian cuisine, vegetable dishes',
    wouldBuyAgain: true,
  },
  {
    id: '8',
    name: 'Champagne Brut',
    winery: 'Moet & Chandon',
    vintage: 2019,
    region: 'Champagne',
    country: 'France',
    grapes: ['Chardonnay', 'Pinot Noir', 'Pinot Meunier'],
    type: 'sparkling',
    ratings: {
      appearance: 5,
      nose: 5,
      palate: 4,
      finish: 5,
      value: 3,
      overall: 8,
    },
    tastingNotes: 'Elegant with brioche and toast notes',
    foodPairing: 'Celebrations, oysters',
    wouldBuyAgain: true,
  },
  {
    id: '9',
    name: 'Vermentino',
    winery: 'Sella & Mosca',
    vintage: 2023,
    region: 'Sardinia',
    country: 'Italy',
    grapes: ['Vermentino'],
    type: 'white',
    ratings: {
      appearance: 4,
      nose: 4,
      palate: 4,
      finish: 3,
      value: 4,
      overall: 7,
    },
    tastingNotes: 'Fresh with citrus and herbal notes',
    foodPairing: 'Mediterranean dishes, seafood',
    wouldBuyAgain: true,
  },
  {
    id: '10',
    name: 'Muscadet',
    winery: 'Joseph Drouhin',
    vintage: 2022,
    region: 'Loire Valley',
    country: 'France',
    grapes: ['Melon de Bourgogne'],
    type: 'white',
    ratings: {
      appearance: 4,
      nose: 3,
      palate: 3,
      finish: 3,
      value: 4,
      overall: 6,
    },
    tastingNotes: 'Dry and bracing with oyster-shell minerality',
    foodPairing: 'Raw oysters, shellfish',
    wouldBuyAgain: false,
  },
]
